[project]
name = "AltTester-Instrumenter"
version = "1.0.9"
description = "Instruments Unity games with AltTester."
license = {text = "MIT"}
authors = [
    {name = "Big Fish Games <support@bigfishgames.zendesk.com>"}
]
readme = "README.md"
